name: Publish images to GHCR
on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io

jobs:
  publish-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Compute lowercased image name
        id: set-image
        run: |
          IMAGE="${{ github.repository }}"
          echo "image_name=$(echo $IMAGE | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v4.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push SGX Docker image
        id: build-and-push-sgx
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ steps.set-image.outputs.image_name }}-server:latest
            ${{ env.REGISTRY }}/${{ steps.set-image.outputs.image_name }}-server:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push SGX simulation Docker image
        id: build-and-push-sim
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile_sim
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ steps.set-image.outputs.image_name }}-server:sim
            ${{ env.REGISTRY }}/${{ steps.set-image.outputs.image_name }}-server:sim-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push SGX attestation Docker image
        id: build-and-push-attestation
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile_attester
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ steps.set-image.outputs.image_name }}-attester:latest
            ${{ env.REGISTRY }}/${{ steps.set-image.outputs.image_name }}-attester:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sign SGX Docker images with cosign
        if: github.event_name != 'pull_request'
        env:
          TAGS: |
            ${{ env.REGISTRY }}/${{ steps.set-image.outputs.image_name }}-server:latest
            ${{ env.REGISTRY }}/${{ steps.set-image.outputs.image_name }}-server:${{ github.sha }}
          DIGEST: ${{ steps.build-and-push-sgx.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

      - name: Sign SGX simulation Docker images with cosign
        if: github.event_name != 'pull_request'
        env:
          TAGS: |
            ${{ env.REGISTRY }}/${{ steps.set-image.outputs.image_name }}-server:sim
            ${{ env.REGISTRY }}/${{ steps.set-image.outputs.image_name }}-server:sim-${{ github.sha }}
          DIGEST: ${{ steps.build-and-push-sim.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

      - name: Sign SGX attestation Docker images with cosign
        if: github.event_name != 'pull_request'
        env:
          TAGS: |
            ${{ env.REGISTRY }}/${{ steps.set-image.outputs.image_name }}-attester:latest
            ${{ env.REGISTRY }}/${{ steps.set-image.outputs.image_name }}-attester:${{ github.sha }}
          DIGEST: ${{ steps.build-and-push-attestation.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
